-- Initial schema.
-- Case-insensitive uniqueness relies on the app-maintained *_normalized columns,
-- populated via StringUtils.normalizeForSearch on every persist/update.

-- =========================
-- INSTITUICAO
-- =========================
CREATE TABLE instituicao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             TEXT NOT NULL,
    nome_normalized  TEXT,
    sigla            VARCHAR(50),
    sigla_normalized VARCHAR(50),
    area             TEXT NOT NULL,
    area_normalized  TEXT,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_instituicao_nome_norm ON instituicao (nome_normalized);
CREATE INDEX idx_instituicao_area_norm ON instituicao (area_normalized);
CREATE INDEX idx_instituicao_sigla_norm ON instituicao (sigla_normalized);

-- =========================
-- BANCA
-- =========================
CREATE TABLE banca (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             TEXT NOT NULL,
    nome_normalized  TEXT,
    sigla            VARCHAR(50),
    sigla_normalized VARCHAR(50),
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_banca_nome_norm ON banca (nome_normalized);
CREATE INDEX idx_banca_sigla_norm ON banca (sigla_normalized);

-- =========================
-- CONCURSO
-- =========================
CREATE TABLE concurso (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instituicao_id BIGINT NOT NULL REFERENCES instituicao(id),
    banca_id       BIGINT NOT NULL REFERENCES banca(id),
    ano            INTEGER NOT NULL,
    mes            INTEGER NOT NULL,
    edital         TEXT,
    data_prova     TIMESTAMP,
    finalizado     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_concurso_instituicao_banca_ano_mes UNIQUE (instituicao_id, banca_id, ano, mes)
);

CREATE INDEX idx_concurso_instituicao ON concurso (instituicao_id);
CREATE INDEX idx_concurso_banca ON concurso (banca_id);
CREATE INDEX idx_concurso_ano ON concurso (ano);
CREATE INDEX idx_concurso_mes ON concurso (mes);

-- =========================
-- CARGO
-- =========================
CREATE TABLE cargo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            TEXT NOT NULL,
    nome_normalized TEXT,
    nivel           TEXT NOT NULL CHECK (nivel IN ('FUNDAMENTAL', 'MEDIO', 'SUPERIOR')),
    area            TEXT NOT NULL,
    area_normalized TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_cargo_nome_nivel_area ON cargo (nome_normalized, nivel, area_normalized);
CREATE INDEX idx_cargo_area_norm ON cargo (area_normalized);

-- =========================
-- CONCURSO ↔ CARGO
-- =========================
CREATE TABLE concurso_cargo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concurso_id BIGINT NOT NULL REFERENCES concurso(id) ON DELETE CASCADE,
    cargo_id    BIGINT NOT NULL REFERENCES cargo(id),
    inscrito    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_concurso_cargo UNIQUE (concurso_id, cargo_id)
);

CREATE INDEX idx_concurso_cargo_concurso ON concurso_cargo (concurso_id);
CREATE INDEX idx_concurso_cargo_cargo ON concurso_cargo (cargo_id);

-- =========================
-- DISCIPLINA
-- =========================
CREATE TABLE disciplina (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            TEXT NOT NULL,
    nome_normalized TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_disciplina_nome_norm ON disciplina (nome_normalized);

-- =========================
-- TEMA
-- =========================
CREATE TABLE tema (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id   BIGINT NOT NULL REFERENCES disciplina(id),
    nome            TEXT NOT NULL,
    nome_normalized TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_tema_disciplina_nome ON tema (disciplina_id, nome_normalized);
CREATE INDEX idx_tema_disciplina ON tema (disciplina_id);
CREATE INDEX idx_tema_nome_norm ON tema (nome_normalized);

-- =========================
-- SUBTEMA
-- =========================
CREATE TABLE subtema (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tema_id         BIGINT NOT NULL REFERENCES tema(id),
    nome            TEXT NOT NULL,
    nome_normalized TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_subtema_tema_nome ON subtema (tema_id, nome_normalized);
CREATE INDEX idx_subtema_tema ON subtema (tema_id);
CREATE INDEX idx_subtema_nome_norm ON subtema (nome_normalized);

-- =========================
-- QUESTAO
-- =========================
CREATE TABLE questao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enunciado      TEXT NOT NULL,
    anulada        BOOLEAN NOT NULL DEFAULT FALSE,
    desatualizada  BOOLEAN NOT NULL DEFAULT FALSE,
    autoral        BOOLEAN NOT NULL DEFAULT FALSE,
    image_url      TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_questao_anulada ON questao (anulada);
CREATE INDEX idx_questao_autoral ON questao (autoral);

-- =========================
-- QUESTAO ↔ SUBTEMA
-- =========================
CREATE TABLE questao_subtema (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questao_id BIGINT NOT NULL REFERENCES questao(id) ON DELETE CASCADE,
    subtema_id BIGINT NOT NULL REFERENCES subtema(id),
    principal  BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_questao_subtema UNIQUE (questao_id, subtema_id)
);

CREATE INDEX idx_questao_subtema_subtema ON questao_subtema (subtema_id);
CREATE INDEX idx_questao_subtema_principal ON questao_subtema (questao_id, principal);

-- =========================
-- ALTERNATIVA
-- =========================
CREATE TABLE alternativa (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questao_id    BIGINT NOT NULL REFERENCES questao(id) ON DELETE CASCADE,
    ordem         INTEGER NOT NULL,
    texto         TEXT NOT NULL,
    correta       BOOLEAN NOT NULL,
    justificativa TEXT,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_alternativa_questao_ordem UNIQUE (questao_id, ordem)
);

CREATE INDEX idx_alternativa_questao ON alternativa (questao_id);
CREATE INDEX idx_alternativa_correta ON alternativa (questao_id, correta);

-- =========================
-- SIMULADO
-- =========================
CREATE TABLE simulado (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                TEXT NOT NULL,
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    banca_id            BIGINT,
    cargo_id            BIGINT,
    nivel               TEXT,
    ignorar_respondidas BOOLEAN DEFAULT FALSE,
    include_autoral     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE simulado_questao (
    simulado_id BIGINT NOT NULL REFERENCES simulado(id) ON DELETE CASCADE,
    questao_id  BIGINT NOT NULL REFERENCES questao(id) ON DELETE CASCADE,
    ordem       INTEGER NOT NULL,

    PRIMARY KEY (simulado_id, questao_id)
);

CREATE INDEX idx_simulado_questao_questao ON simulado_questao (questao_id);

-- Generation filters (@ElementCollection)
CREATE TABLE simulado_area (
    simulado_id BIGINT NOT NULL REFERENCES simulado(id) ON DELETE CASCADE,
    area        TEXT NOT NULL
);

CREATE TABLE simulado_disciplina (
    simulado_id BIGINT NOT NULL REFERENCES simulado(id) ON DELETE CASCADE,
    item_id     BIGINT NOT NULL,
    quantidade  INTEGER NOT NULL
);

CREATE TABLE simulado_tema (
    simulado_id BIGINT NOT NULL REFERENCES simulado(id) ON DELETE CASCADE,
    item_id     BIGINT NOT NULL,
    quantidade  INTEGER NOT NULL
);

CREATE TABLE simulado_subtema (
    simulado_id BIGINT NOT NULL REFERENCES simulado(id) ON DELETE CASCADE,
    item_id     BIGINT NOT NULL,
    quantidade  INTEGER NOT NULL
);

-- =========================
-- RESPOSTA
-- =========================
CREATE TABLE resposta (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questao_id              BIGINT NOT NULL REFERENCES questao(id) ON DELETE CASCADE,
    alternativa_id          BIGINT NOT NULL REFERENCES alternativa(id) ON DELETE CASCADE,
    justificativa           TEXT,
    dificuldade_id          INTEGER,
    tempo_resposta_segundos INTEGER,
    simulado_id             BIGINT REFERENCES simulado(id) ON DELETE SET NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_resposta_alternativa ON resposta (alternativa_id);
CREATE INDEX idx_resposta_questao ON resposta (questao_id);
CREATE INDEX idx_resposta_created_at ON resposta (created_at);
CREATE INDEX idx_resposta_simulado ON resposta (simulado_id);
CREATE INDEX idx_resposta_questao_created ON resposta (questao_id, created_at DESC);

-- =========================
-- ESTUDO SUBTEMA
-- =========================
CREATE TABLE estudo_subtema (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtema_id BIGINT NOT NULL REFERENCES subtema(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_estudo_subtema_subtema ON estudo_subtema (subtema_id);
CREATE INDEX idx_estudo_subtema_created_at ON estudo_subtema (created_at);

-- =========================
-- SECAO CARGO
-- =========================
CREATE TABLE secao_cargo (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concurso_cargo_id BIGINT NOT NULL REFERENCES concurso_cargo(id) ON DELETE CASCADE,
    nome              TEXT NOT NULL,
    peso              DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    nota_minima       DOUBLE PRECISION,
    ordem             INTEGER,
    num_questoes      INTEGER,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_secao_cargo_concurso_cargo ON secao_cargo (concurso_cargo_id);

-- =========================
-- SECAO DISCIPLINA
-- =========================
CREATE TABLE secao_disciplina (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secao_cargo_id BIGINT NOT NULL REFERENCES secao_cargo(id) ON DELETE CASCADE,
    nome           TEXT NOT NULL,
    ordem          INTEGER NOT NULL DEFAULT 0,
    num_questoes   INTEGER,
    peso           DOUBLE PRECISION,
    nota_minima    DOUBLE PRECISION,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE secao_disciplina_subtema (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secao_disciplina_id BIGINT NOT NULL REFERENCES secao_disciplina(id) ON DELETE CASCADE,
    subtema_id          BIGINT NOT NULL REFERENCES subtema(id) ON DELETE CASCADE,

    CONSTRAINT uq_secao_disciplina_subtema UNIQUE (secao_disciplina_id, subtema_id)
);

-- =========================
-- PROVA / PROVA SECAO
-- =========================
CREATE TABLE prova (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concurso_id       BIGINT NOT NULL REFERENCES concurso(id) ON DELETE CASCADE,
    concurso_cargo_id BIGINT NOT NULL REFERENCES concurso_cargo(id) ON DELETE CASCADE,
    nome              TEXT NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_prova_concurso ON prova (concurso_id);
CREATE INDEX idx_prova_concurso_cargo ON prova (concurso_cargo_id);

CREATE TABLE prova_secao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prova_id       BIGINT NOT NULL REFERENCES prova(id) ON DELETE CASCADE,
    secao_cargo_id BIGINT NOT NULL REFERENCES secao_cargo(id) ON DELETE CASCADE,
    nome           TEXT NOT NULL,
    ordem          INTEGER NOT NULL,
    num_questoes   INTEGER,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_prova_secao_prova_ordem UNIQUE (prova_id, ordem)
);

CREATE INDEX idx_prova_secao_prova ON prova_secao (prova_id);
CREATE INDEX idx_prova_secao_secao_cargo ON prova_secao (secao_cargo_id);

CREATE TABLE questao_prova_secao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questao_id      BIGINT NOT NULL REFERENCES questao(id) ON DELETE CASCADE,
    prova_secao_id  BIGINT NOT NULL REFERENCES prova_secao(id) ON DELETE CASCADE,
    numero_questao  INTEGER,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_questao_prova_secao UNIQUE (questao_id, prova_secao_id)
);

CREATE INDEX idx_questao_prova_secao_questao ON questao_prova_secao (questao_id);
CREATE INDEX idx_questao_prova_secao_secao ON questao_prova_secao (prova_secao_id);
